# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"grid_subsampling": "00_core.ipynb",
         "Arrow3D": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://lyuhaitao.github.io/lyutool/"

git_url = "https://github.com/lyuhaitao/lyutool/tree/master/"

def custom_doc_links(name): return None
